language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer selfupdate
  - composer update

script:
  - phpunit